//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingOfCartridges.AppDataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int id { get; set; }
        public string Title { get; set; }
        public int TypeId { get; set; }
        public int Count { get; set; }
        public string Сabinet { get; set; }
        public System.DateTime DateAcceptance { get; set; }
        public string SerialNumber { get; set; }
        public int StatusId { get; set; }
        public string FIO { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }

        public string StringType { get { return Type.Title; } }
    }
}
